name: build
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y parallel php rename
      - name: Run stuff
        run: |
          git submodule update --init --remote
          echo '*' > rss-bridge/whitelist.txt
          cp -r bridges patches rss-bridge
          git -C rss-bridge apply patches/*.diff
          php -t rss-bridge -S 127.0.0.1:8080 &
          sleep 1

          mkdir ../out
          path='?action=display&format=Mrss&bridge='
          parallel -q wget -P ../out localhost:8080/$path{} < list || true
      - name: Commit data
        run: |
          git config user.name "Updater"
          git config user.email "updater@rss-bridge.org"
          git fetch origin out
          cp index.html ..
          git checkout out
          rm -rf *
          cp ../index.html .
          rename 's/%2F/_/g' ../out/*
          rename 's/.*?bridge=//' ../out/*
          git add .
          git commit --amend -m "$(date -u)"
          git push -f origin out
