name: build
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: rssbridge/rss-bridge:latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y parallel rename git python3
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Bump submodules
        run: |
          git config --global --add safe.directory /__w/rss/rss
          git submodule update --init --remote
      - name: Run stuff
        run: |
          cd rss-bridge
          echo '*' > whitelist.txt
          cp -r ../bridges .
          git apply ../patches/*.diff

          mkdir ../../out
          path='action=display\&format=Mrss\&bridge='
          parallel "php index.php $path{} > ../../out/{}" < ../list
          cd ..
      - name: Commit data
        run: |
          git config user.name "Updater"
          git config user.email "updater@rss-bridge.org"
          git fetch origin out
          cp index.html ../out
          git checkout out
          rm -rf *
          mv ../out/* .
          urldecode="import sys; from urllib.parse import unquote; print(unquote(sys.argv[1]))"
          parallel "mv -n {} \$(python3 -c '$urldecode' {} | tr / _)" ::: * || true
          git add .
          git commit --amend -m "$(date -u)"
          git push -f origin out
