name: build
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt install -y parallel php rename
      - name: Run stuff
        run: |
          git submodule update --init --remote
          cd rss-bridge
          echo '*' > whitelist.txt
          cp -r ../* .
          git apply patches/*.diff

          mkdir ../../out
          path='action=display&format=Mrss&bridge='
          parallel "php index.php $path{} > ../../out/{}" < ../list
          cd ..
      - name: Commit data
        run: |
          git config user.name "Updater"
          git config user.email "updater@rss-bridge.org"
          git fetch origin out
          cp index.html ../out
          git checkout out
          rm -rf *
          mv ../out/* .
          rename 's/%2F/_/g' *
          git add .
          git commit --amend -m "$(date -u)"
          git push -f origin out
